"""Add discord role sync tables

Revision ID: 82b6e3d859e6
Revises: 20260612_0001
Create Date: 2026-06-13 23:03:02.041939
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '82b6e3d859e6'
down_revision: str | None = '20260612_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_role_assignments',
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('discord_user_id', sa.String(length=64), nullable=False),
    sa.Column('role_type', sa.String(length=40), nullable=False),
    sa.Column('desired_role_id', sa.String(length=64), nullable=False),
    sa.Column('last_known_has_role', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', 'role_type', name='uq_discord_role_assignments')
    )
    op.create_index('ix_discord_role_assignments_status', 'discord_role_assignments', ['tournament_id', 'sync_status'], unique=False)
    op.create_table('discord_role_links',
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('role_type', sa.String(length=40), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('role_name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('managed_by_bot', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'guild_id', 'role_type', name='uq_discord_role_links')
    )
    op.create_index('ix_discord_role_links_tournament', 'discord_role_links', ['tournament_id'], unique=False)
    op.drop_index(op.f('ix_formula_placement_points_lookup'), table_name='score_formula_placement_points')
    op.drop_table('score_formula_placement_points')
    op.drop_constraint(op.f('rule_sets_source_preset_id_fkey'), 'rule_sets', type_='foreignkey')
    op.drop_table('rule_presets')
    op.alter_column('audit_logs', 'before_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'after_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('discord_message_jobs', 'payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('event_outbox', 'payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('leaderboard_snapshots', 'snapshot_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('overlay_configs', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint(op.f('overlay_configs_tournament_id_key'), 'overlay_configs', type_='unique')
    op.drop_index(op.f('ix_overlay_configs_tournament_id'), table_name='overlay_configs')
    op.create_index(op.f('ix_overlay_configs_tournament_id'), 'overlay_configs', ['tournament_id'], unique=True)
    op.alter_column('player_status_snapshots', 'latest_score_summary_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('player_status_snapshots', 'allowed_actions_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('public_tournament_summaries', 'display_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('rule_sets', 'name',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('rule_sets', 'model',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('rule_sets', 'advancement_policy_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('rule_sets', 'lobby_assignment_policy_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('rule_sets', 'verification_policy_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('rule_sets', 'config_snapshot_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.drop_index(op.f('ix_rule_sets_source_preset'), table_name='rule_sets')
    op.drop_index(op.f('ix_rule_sets_tournament_status'), table_name='rule_sets')
    op.alter_column('score_formulas', 'rule_set_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('score_formulas', 'name',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('score_formulas', 'placement_points_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('score_formulas', 'bonus_rules_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('score_formulas', 'penalty_rules_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('score_formulas', 'bye_rule_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('score_formulas', 'tie_break_order_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('score_formulas', 'manual_override_policy_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('score_formulas', 'config_snapshot_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.drop_index(op.f('ix_score_formulas_tournament_status'), table_name='score_formulas')
    op.alter_column('scores', 'formula_snapshot_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('tournament_dashboard_summaries', 'registration_counts_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('tournament_dashboard_summaries', 'current_check_in_counts_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('tournament_dashboard_summaries', 'discord_delivery_status_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('tournaments', 'name',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_index(op.f('ix_tournaments_status'), table_name='tournaments')
    op.drop_constraint(op.f('tournaments_public_slug_key'), 'tournaments', type_='unique')
    op.drop_index(op.f('ix_tournaments_public_slug'), table_name='tournaments')
    op.create_index(op.f('ix_tournaments_public_slug'), 'tournaments', ['public_slug'], unique=True)
    op.drop_constraint(op.f('fk_tournaments_active_score_formula'), 'tournaments', type_='foreignkey')
    op.drop_constraint(op.f('fk_tournaments_active_rule_set'), 'tournaments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_tournaments_active_rule_set'), 'tournaments', 'rule_sets', ['active_rule_set_id'], ['id'])
    op.create_foreign_key(op.f('fk_tournaments_active_score_formula'), 'tournaments', 'score_formulas', ['active_score_formula_id'], ['id'])
    op.drop_index(op.f('ix_tournaments_public_slug'), table_name='tournaments')
    op.create_index(op.f('ix_tournaments_public_slug'), 'tournaments', ['public_slug'], unique=False)
    op.create_unique_constraint(op.f('tournaments_public_slug_key'), 'tournaments', ['public_slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.alter_column('tournaments', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    op.alter_column('tournament_dashboard_summaries', 'discord_delivery_status_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('tournament_dashboard_summaries', 'current_check_in_counts_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('tournament_dashboard_summaries', 'registration_counts_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scores', 'formula_snapshot_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_score_formulas_tournament_status'), 'score_formulas', ['tournament_id', 'status'], unique=False)
    op.alter_column('score_formulas', 'config_snapshot_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('score_formulas', 'manual_override_policy_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('score_formulas', 'tie_break_order_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('score_formulas', 'bye_rule_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('score_formulas', 'penalty_rules_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('score_formulas', 'bonus_rules_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('score_formulas', 'placement_points_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('score_formulas', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('score_formulas', 'rule_set_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(op.f('rule_sets_source_preset_id_fkey'), 'rule_sets', 'rule_presets', ['source_preset_id'], ['id'])
    op.create_index(op.f('ix_rule_sets_tournament_status'), 'rule_sets', ['tournament_id', 'status'], unique=False)
    op.create_index(op.f('ix_rule_sets_source_preset'), 'rule_sets', ['source_preset_id'], unique=False)
    op.alter_column('rule_sets', 'config_snapshot_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('rule_sets', 'verification_policy_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('rule_sets', 'lobby_assignment_policy_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('rule_sets', 'advancement_policy_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('rule_sets', 'model',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('rule_sets', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('public_tournament_summaries', 'display_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('player_status_snapshots', 'allowed_actions_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('player_status_snapshots', 'latest_score_summary_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_overlay_configs_tournament_id'), table_name='overlay_configs')
    op.create_index(op.f('ix_overlay_configs_tournament_id'), 'overlay_configs', ['tournament_id'], unique=False)
    op.create_unique_constraint(op.f('overlay_configs_tournament_id_key'), 'overlay_configs', ['tournament_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('overlay_configs', 'config_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('leaderboard_snapshots', 'snapshot_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('event_outbox', 'payload_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('discord_message_jobs', 'payload_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('audit_logs', 'after_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'before_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('rule_presets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('game', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('participant_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rule_presets_pkey'))
    )
    op.create_table('score_formula_placement_points',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('score_formula_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('placement', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['score_formula_id'], ['score_formulas.id'], name=op.f('score_formula_placement_points_score_formula_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('score_formula_placement_points_pkey')),
    sa.UniqueConstraint('score_formula_id', 'placement', name=op.f('uq_formula_placement'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_formula_placement_points_lookup'), 'score_formula_placement_points', ['score_formula_id', 'placement'], unique=False)
    op.drop_index('ix_discord_role_links_tournament', table_name='discord_role_links')
    op.drop_table('discord_role_links')
    op.drop_index('ix_discord_role_assignments_status', table_name='discord_role_assignments')
    op.drop_table('discord_role_assignments')
    # ### end Alembic commands ###
