"""Add discord role sync tables

Revision ID: 82b6e3d859e6
Revises: 20260612_0001
Create Date: 2026-06-13 23:03:02.041939
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '82b6e3d859e6'
down_revision: str | None = '20260612_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_role_assignments',
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('discord_user_id', sa.String(length=64), nullable=False),
    sa.Column('role_type', sa.String(length=40), nullable=False),
    sa.Column('desired_role_id', sa.String(length=64), nullable=False),
    sa.Column('last_known_has_role', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', 'role_type', name='uq_discord_role_assignments')
    )
    op.create_index('ix_discord_role_assignments_status', 'discord_role_assignments', ['tournament_id', 'sync_status'], unique=False)
    op.create_table('discord_role_links',
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('role_type', sa.String(length=40), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('role_name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('managed_by_bot', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'guild_id', 'role_type', name='uq_discord_role_links')
    )
    op.create_index('ix_discord_role_links_tournament', 'discord_role_links', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_discord_role_links_tournament', table_name='discord_role_links')
    op.drop_table('discord_role_links')
    op.drop_index('ix_discord_role_assignments_status', table_name='discord_role_assignments')
    op.drop_table('discord_role_assignments')
    # ### end Alembic commands ###
